// <auto-generated />
using System;
using ITC.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ITC.DataAccess.Migrations
{
    [DbContext(typeof(IncomeTaxDbContext))]
    [Migration("20230813074828_InitMigration")]
    partial class InitMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ITC.DataAccess.Entities.TaxBand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(7)")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("LowerLimit")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Rate")
                        .HasColumnType("int");

                    b.Property<int?>("UpperLimit")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TaxBand");

                    b.HasData(
                        new
                        {
                            Id = new Guid("dcb1ab88-d3c3-4022-bb75-cc9ef852202d"),
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LowerLimit = 0,
                            Name = "Band 1",
                            Rate = 0,
                            UpperLimit = 5000
                        },
                        new
                        {
                            Id = new Guid("63ebc360-2065-44a1-80a6-cafd42fba309"),
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LowerLimit = 5000,
                            Name = "Band 2",
                            Rate = 20,
                            UpperLimit = 20000
                        },
                        new
                        {
                            Id = new Guid("72c3a4c3-65f6-44b9-93db-f52a841d4eea"),
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LowerLimit = 20000,
                            Name = "Band 3",
                            Rate = 40
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
